#!/bin/bash

set -euf -o pipefail

BASE=/opt/homeless
ROOT=${BASE}/storage
TIMESTAMP=${BASE}/timestamp.txt
TEMPLATES=${BASE}/templates
BACKUPS=${ROOT}/BACKUPS
CONTRACTS=${ROOT}/contracts
IMAGES=${ROOT}/images
PROFILES=${ROOT}/profiles
TOMCAT_HOME=${BASE}/tools/tomcat
MAVEN_HOME=$BASE/tools/maven
COMMIT=homeless.id
OWNER=tomcat.tomcat

PATH=$MAVEN_HOME/bin:$PATH
THIS_IP=`/sbin/ifconfig eth0 | awk '/inet addr/{print substr($2,6)}'`

echo "Main app..."

echo "Replacing configuration according current layout"
echo "Building applications (WAR files)"
mvn clean package


echo "Reports app..."

echo "Replacing configuration according current layout"
pushd re
echo "Building applications (WAR files)"
mvn clean package

echo "Replacing templates in ${TEMPLATES}"
find ${TEMPLATES} -type f -delete
find templates -type f -exec cp -f \{} ${TEMPLATES} \;
popd


echo "Stopping running application, backing up logs, cleaning environment and run everything again..."

echo "Stopping Tomcat if it is running"
/etc/init.d/tomcat stop
echo "Deleting old applications"
pushd ${TOMCAT_HOME}/webapps
rm -rf homeless homeless-report-engine
find -name \*.war -delete
popd
echo "Deploying new applications"
find -name \*.war -exec cp -f \{} ${TOMCAT_HOME}/webapps/ \;
pushd ${TOMCAT_HOME}/logs
logs_file_stamp=`date +"%d_%m_%Y__%H_%M_%S"`
logs_file_name=${BACKUPS}/logs_backup_${logs_file_stamp}.zip
echo "Backing up logs to ${logs_file_name}"
zip -9 -r ${logs_file_name} .
chown $OWNER ${logs_file_name} # Yak!
find . -name *.out -o -name *.txt -o -name *.log -delete
popd
echo "Placing timestamp before starting homeless application"
CID=""
[ -r $COMMIT ] && CID=$(cut -c-7 $COMMIT)
echo $(date +'%H:%M:%S %d.%m.%Y') $CID > ${TIMESTAMP}
echo "Starting Tomcat applications..."
/etc/init.d/tomcat start

echo "DEPLOYMENT SUCCESSFUL"
