select 1 ;
ALTER TABLE `homeless`.`ServContract` CHANGE COLUMN `commentResult` `commentResult` TEXT NULL DEFAULT NULL ;
ALTER TABLE `homeless`.`ShelterHistory` ADD COLUMN `comments` MEDIUMTEXT NULL AFTER `servContract`;
ALTER TABLE `homeless`.`ZAGSRequestDocumentRegistry` CHANGE COLUMN `name` `respAddress` TEXT NULL DEFAULT NULL ;
ALTER TABLE `homeless`.`ContractPoints` ADD COLUMN `abbreviation` VARCHAR(45) NULL AFTER `caption`;
update ContractPoints set abbreviation = 'Пасп' where id = 1;
update ContractPoints set abbreviation = 'ОфП' where id = 2;
update ContractPoints set abbreviation = 'ОМС' where id = 3;
update ContractPoints set abbreviation = 'ИНН' where id = 4;
update ContractPoints set abbreviation = 'ТрдКн' where id = 5;
update ContractPoints set abbreviation = 'МСЭК' where id = 6;
update ContractPoints set abbreviation = 'Инт' where id = 7;
update ContractPoints set abbreviation = 'Рег' where id = 8;
update ContractPoints set abbreviation = 'Рег2' where id = 9;
update ContractPoints set abbreviation = 'Труд' where id = 10;
update ContractPoints set abbreviation = 'Труд2' where id = 11;
update ContractPoints set abbreviation = 'ДНП' where id = 12;
update ContractPoints set abbreviation = 'РебЦ' where id = 13;
update ContractPoints set abbreviation = 'Леч' where id = 14;
update ContractPoints set abbreviation = '' where id = 15;
update ContractPoints set abbreviation = 'Род' where id = 16;
update ContractPoints set abbreviation = 'Дом' where id = 17;
update ContractPoints set abbreviation = 'Гржд' where id = 18;
update ContractPoints set abbreviation = 'Суж' where id = 19;
update ContractPoints set abbreviation = 'Жилье' where id = 20;
update ContractPoints set abbreviation = 'ЖильеСуд' where id = 21;
update ContractPoints set abbreviation = 'Запросы' where id = 22;
update ContractPoints set abbreviation = 'ДНПД' where id = 23;
update ContractPoints set abbreviation = 'Обрз' where id = 24;
update ContractPoints set abbreviation = 'СвРожд' where id = 25;
update ContractPoints set abbreviation = 'ВоенБлт' where id = 26;
update ContractPoints set abbreviation = 'Загран' where id = 27;
update ContractPoints set abbreviation = 'РеабСр-ва' where id = 28;
